version: '3'

services:
  redis: # when running individually, redis container instance needed.
    image: redis:latest
    ports:
      - '6379:6379'
  api:
    build:
      context: .
      dockerfile: Dockerfile.multi
    ports:
      - '8081:8080'
    environment:
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH_SERVER_URI: ${AUTH_SERVER_URI}
      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
        - redis
