auth0:
  audience: ${AUTH0_AUDIENCE}

spring:
  application:
    name: printscript-api
  security:
    oauth2:
        resourceserver:
            jwt:
              issuer-uri: ${AUTH_SERVER_URI}
              client-id: ${AUTH_CLIENT_ID}
              client-secret: ${AUTH_CLIENT_SECRET}
