name: continuous integration

on:
  workflow_call:
    inputs:
      env_vars:
        required: true

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      -   name: Checkout
          uses: actions/checkout@v4

      -   name: Set up JDK 21
          uses: actions/setup-java@v2
          with:
            java-version: 21
            distribution: 'adopt'

      -   name: Run Build
          run: ./gradlew build