name: continuous delivery

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_run:
    workflows: [ "continuous deployment" ]
    types:
      - completed

jobs:
  delivery:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Continuous Delivery

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Log in to the Container registry
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: tomasvalleduran/ingsis-parse
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.GITHUB_ACTOR }}
          password: ${{ env.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: tomasvalleduran/ingsis-parse
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build . -f Dockerfile.multi --tag ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest \
           --build-arg GITHUB_USER=${{ env.GITHUB_ACTOR }} --build-arg GITHUB_TOKEN=${{ env.GITHUB_TOKEN }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
