name: continuous integration

on:
  workflow_call:
    inputs:
      token:
        description: 'Personal Access Token'
        required: true
        default: ${{ secrets.GITHUB_TOKEN }}


jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      -   name: Checkout
          uses: actions/checkout@v4

      -   name: Set up JDK 21
          uses: actions/setup-java@v2
          with:
            java-version: 21
            distribution: 'adopt'

      -   name: Run Build
          env:
            GITHUB_TOKEN: ${{ inputs.token }}
          run: ./gradlew build