name: continuous deployment

on:
  workflow_call:
    inputs:
      actor:
        description: 'GitHub Actor'
        required: true
        default: ${{ github.actor }}
    secrets:
      token:
        description: 'Personal Access Token'
        required: true
        default: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deployment:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Publish package
        run: ./gradlew publish --info
        env:
          GITHUB_TOKEN: ${{ inputs.token }}
          GITHUB_ACTOR: ${{ inputs.actor }}
