name: continuous deployment

on:
  workflow_call:
    inputs:
      env_vars:
        required: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    name: Continuous Deployment

    permissions:
      contents: read
      packages: write

    steps:
      -   name: Checkout
          uses: actions/checkout@v4

      -   name: Set up JDK
          uses: actions/setup-java@v2
          with:
            java-version: 21
            distribution: 'adopt'

      -   name: Publish package
          run: ./gradlew publish --info
